db.driver=com.mysql.cj.jdbc.Driver

# Connection string for Aiven Cloud
db.url=jdbc:mysql://mysql-3c8b5004-politecarepharma.i.aivencloud.com:19102/defaultdb?useSSL=true&trustServerCertificate=true

db.username=avnadmin
# Aiven dashboard se password "Reveal" karke yahan paste kardo \u2193
db.password=AVNS_VNSE3PcnihHiFSZ3ov4

hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
# Isse tables Aiven cloud mein apne aap ban jayengi
hibernate.hbm2ddl.auto=update